algoritmo "semnome"
var
   Valor1, Valor2, Resultado : inteiro
   Função Soma(x, y : inteiro) : inteiro
   Inicio
   Resultado <- X + Y
   Retorne Resultado
   // ou Retorne X + Y
   FimFunção
inicio
    Escreva("Digite o primeiro valor:")
    Leia(Valor1)
    Escreva("Digite o segundo valor:")
    Leia(Valor2)
    Resultado <- Soma(Valor1, Valor2)
    Escreva("O resultado é:", Resultado)
fimalgoritmo